apiVersion: v1
kind: Service
metadata:
  name: randmeth-campaigns
  namespace: randmeth
spec:
  type: NodePort
  selector:
    app: randmeth-campaigns
  ports:
    - nodePort: 31479
      port: 80
      targetPort: 8080

# minikube service randmeth-campaigns