apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "helm.fullname" .}}
  labels:
    app: randmeth-campaigns
  namespace: randmeth
spec:
  selector:
    matchLabels:
      app: randmeth-campaigns
  replicas: {{.Values.replicaCount}}
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: randmeth-campaigns
    spec:
      containers:
        - name: {{ include "helm.fullname" .}}
          image: {{.Values.image.repository}}
          imagePullPolicy: {{.Values.image.pullPolicy}}
          ports:
            - containerPort: 8080
              protocol: TCP

# 123113322222.dkr.ecr.eu-west-1.amazonaws.com/randmeth:eks-demo