apiVersion: v1
kind: Service
metadata:
  name: randmeth-campaigns
spec:
  type: NodePort
  selector:
    app: randmeth-campaigns
  ports:
    - nodePort: 31479
      port: 8080
      targetPort: 8080
#  type: ClusterIP

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: randmeth-campaigns
  labels:
    app: randmeth-campaigns
  namespace: default
spec:
  selector:
    matchLabels:
      app: randmeth-campaigns
  replicas: 2
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: randmeth-campaigns
    spec:
      containers:
      - name: randmeth-campaigns
        image: 314051162948.dkr.ecr.eu-west-1.amazonaws.com/randmeth:latest
        imagePullPolicy: Always
        ports:
          - containerPort: 8080
            protocol: TCP
#           name: campaigns