apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: randmeth-fargate-cluster
  region: eu-west-1

vpc:
  id: vpc-09ad7fee9538cd9b3
  cidr: "192.168.0.0/16"
  subnets:
    public:
      eu-west-1a:
        id: subnet-075ff08de8ac16e8f
      eu-west-1b:
        id: subnet-01191662f707bacea
    private:
      eu-west-1a:
        id: subnet-084d7b5a3caea2c34
      eu-west-1b:
        id: subnet-00d247e3ef7f04220

nodeGroups:
  - name: randmeth-pub-nodes
    instanceType: t2.medium
    desiredCapacity: 2
    ssh:
      allow: true
      publicKeyName: eksworkshop

